Address `.ninja` file generation issue on Android 16
* Commit ("Convert platform_tests from Make to Soong")
  https://android.googlesource.com/platform/platform_testing/+/128b2e33260bbb2c69a9e91bf9e69493f6e3fb29
  converted platform_testing module from Make to Soong, which means that
  searching for other modules can only be possible within a namespace
  starting from project top-level directory (i.e., src/Android.bp).
  Analyzing platform_testing module fails because it needs some binaries
  located in "out/host" directory, which in our dockerized environment
  is outside of the "src" directory where Soong exists.

* To work around it, we'll bring the "out" directory back to "src/out"
  via a symlink, aligning it with the default AOSP directory structure.

* Btw, this is a bug, as AOSP devs broke the behavior of the $OUT_DIR
  variable used to specify a custom path to store the output of the
  build. Effectively, the $OUT_DIR is now forced to be relative to the
  "src" directory.

---

[100% 2/2] analyzing Android.bp files and generating ninja file at /mnt/out/soong/build.lineage_rova.ninja
FAILED: /mnt/out/soong/build.lineage_rova.ninja
cd "$(dirname "/mnt/out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "/mnt/out/host/linux-x86/bin/soong_build")" && cd / && env -i "$BUILDER" --top "$TOP" --soong_out "/mnt/out/soong" --out "/mnt/out" --soong_variables /mnt/out/soong/soong.lineage_rova.variables -o /mnt/out/soong/build.lineage_rova.ninja --kati_suffix -lineage_rova -l /mnt/out/.module_paths/Android.bp.list --available_env /mnt/out/soong/soong.environment.available --used_env /mnt/out/soong/soong.environment.used.lineage_rova.build Android.bp
error: platform_testing/Android.bp:5:1: module "platform_tests" variant "android_common": Path is outside directory: /mnt/out/host/linux-x86/bin/perfetto_trace_processor_shell
error: platform_testing/Android.bp:5:1: module "platform_tests" variant "android_common": Path is outside directory: /mnt/out/host/linux-x86/bin/root-canal
ninja: build stopped: subcommand failed.

Signed-off-by: iusmac <iusico.maxim@libero.it>