Link user's home directory from the container to the host
According to the docs, Repo will create & maintain the following
files/directories in the user's home directory:
* .repoconfig/: Repo's per-user directory for all random config
                files/state.
* .repoconfig/config: Per-user settings using [git-config] file format.
* .repoconfig/keyring-version: Cache file for checking if the gnupg
                               subdir has all the same keys as the
                               repo launcher.  Used to avoid running
                               gpg constantly as that can be quite
                               slow.
* .repoconfig/gnupg/: GnuPG's internal state directory used when repo
                      needs to run gpg. This provides isolation from
                      the user's normal ~/.gnupg/.
* .repoconfig/.repo_config.json: JSON cache of the .repoconfig/config
                                 file for repo to read/process quickly.
* .repo_.gitconfig.json: JSON cache of the `.gitconfig` file for repo
                           to read/process quickly.

Before this Repo was randomly throwing the following error during build:
  Traceback (most recent call last):
    File "/home/iusmac/src/.repo/repo/git_config.py", line 361, in _SaveJson
      with open(self._json, 'w') as fd:
OSError: [Errno 30] Read-only file system: '/home/iusmac/.repo_.gitconfig.json'

We could selectively mount .repoconfig directory and
.repo_.gitconfig.json file to the host, but this would not work because
repo-tool can also remove these files/directories, which will break
bind-mount mechanism by throwing a 'Device or resource busy' error,
because mount points are based on inode.

As we know, most Debian packages store config/cache files in the user's
home directory. So, let's kill two birds with one stone and mount the
entire home directory to satisfy Repo tool and to save configs & caches
which will also speed up things in the future when rebuilding the image
or when the container dies.

Signed-off-by: iusmac <iusico.maxim@libero.it>